# Generated by Django 4.0.4 on 2022-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_item_brand_name_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='promo',
            field=models.ManyToManyField(blank=True, to='custom_admin.promo'),
        ),
    ]
