# Generated by Django 4.0.4 on 2022-05-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_item_price_alter_item_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default='Superbrand', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='1', max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='promo',
            field=models.ManyToManyField(default=100, to='custom_admin.promo'),
        ),
    ]
