# Generated by Django 4.0.4 on 2022-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishwasher',
            name='power',
            field=models.IntegerField(default=220),
        ),
    ]
